manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/theninj4
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pmw33xx
      import: app/west.yml
  self:
    path: config
